# Generated by Django 2.2 on 2020-07-21 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='added_by',
            field=models.ManyToManyField(related_name='added_game', to='appOne.User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_game', to='appOne.User'),
        ),
    ]
